Vagrant.configure("2") do |config|
  config.vm.box = "devel-devtoolset-10-cbdb-vagrant-virtualbox-centos7-2009-20221011.box"
  config.vm.box_url = "https://artifactory.hashdata.xyz/artifactory/vagrant-public/devel-devtoolset-10-cbdb-vagrant-virtualbox-centos7-2009-20221011.box"
  config.vm.box_check_update = true

  config.vm.hostname = "hashdata"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "change_vm_name"
    vb.gui = false
    vb.cpus = 8
    vb.memory = "12192"
  end

  config.vm.synced_folder "../../.", "/home/gpadmin/workspace/cbdb", owner: "gpadmin", group: "gpadmin"#, :extra => "dmode=555,fmode=555"
  if ENV['CBDB_TEST_REPO_PATH'] != nil then
    config.vm.synced_folder ENV['CBDB_TEST_REPO_PATH'], "/home/gpadmin/workspace/cbdb_testrepo", owner: "gpadmin", group: "gpadmin"#, :extra => "dmode=755,fmode=755"
  end
  if ENV['CBDB_TEST_TPCH_PATH'] != nil then 
    config.vm.synced_folder ENV['CBDB_TEST_TPCH_PATH'], "/home/gpadmin/workspace/tpch", owner: "gpadmin", group: "gpadmin"#, :extra => "dmode=755,fmode=755"
  end
  config.ssh.username = "gpadmin"
  config.ssh.password = "vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    user=gpadmin
    su - $user -c "sed -i 's/workspace\\/cbdb_dev\\/gpAux\\/gpdemo\\/datadirs/data0\\/database\\/datadirs/' /home/$user/.bashrc"
    su - $user -c "sed -i '/^source \\/home\\/gpadmin\\/install\\/gpdb\\/greenplum_path/ d' /home/$user/.bashrc"
    su - $user -c "mkdir -p /home/$user/data0/database"
    su - $user -c "echo "source ~/workspace/cbdb/deploy/cbdb_env.sh" >> /home/$user/.bashrc"
    chmod u+x /home/$user/workspace/cbdb/deploy/cbdb_deploy.sh &&
    su - $user -c "/home/$user/workspace/cbdb/deploy/cbdb_deploy.sh build"
  SHELL
end
