#!/bin/sh
#
# Verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#

rc=0

if [ -x "./tools/cpplint.py" ]; then
	echo "Running cpplint ..."
	mkdir -p .tmp/
	./tools/cpplint.py --counting=detailed --recursive . > .tmp/cpplint.log 2>&1
	rc=$?
	if [ $rc -ne 0 ]; then
		tail -n 1 .tmp/cpplint.log
		echo ""
		echo "ERROR cpplint returned errors!"
		echo "ERROR Fix the problem and use 'git add' to update your changes."
		echo "ERROR See `pwd`/.tmp/cpplint.log for more information."
		echo ""
	fi
fi

exit $rc