#pragma once

#define PAX_AUX_PTBLOCKNAME       "ptblockname"
#define PAX_AUX_PTTUPCOUNT        "pttupcount"
#define PAX_AUX_PTBLOCKSIZE       "ptblocksize"
#define PAX_AUX_PTSTATISITICS     "ptstatistics"
#define PAX_AUX_PTVISIMAPNAME     "ptvisimapname"
#define PAX_AUX_PTEXISTEXTTOAST   "ptexistexttoast"
#define PAX_AUX_PTISCLUSTERED     "ptisclustered"


#define ANUM_PG_PAX_BLOCK_TABLES_PTBLOCKNAME 1
#define ANUM_PG_PAX_BLOCK_TABLES_PTTUPCOUNT 2
#define ANUM_PG_PAX_BLOCK_TABLES_PTBLOCKSIZE 3
#define ANUM_PG_PAX_BLOCK_TABLES_PTSTATISITICS 4
#define ANUM_PG_PAX_BLOCK_TABLES_PTVISIMAPNAME 5
#define ANUM_PG_PAX_BLOCK_TABLES_PTEXISTEXTTOAST 6
#define ANUM_PG_PAX_BLOCK_TABLES_PTISCLUSTERED 7
#define NATTS_PG_PAX_BLOCK_TABLES 7